### ISSUE TITLE
Инициализация переменных

### ISSUE THREAD

**Issue by avasyukov** [Avalanche736/1-zadanie#1]
Вот здесь:
https://github.com/Avalanche736/1-zadanie/blob/f01264c5d289b2de5d54c18f04308b029ab79b15/3.7.c#L16
явно предполагается использование a[] как массива флажков. Но:
- значения элементов массива не инициализированы, в них исходно лежит некий случайный мусор
- оператор = это присваивание, а не проверка (проверка это ==)

**Comment by Avalanche736** [comment]
Спасибо, = вместо == не заметил. А про мусор в массиве: если массив объявить до мэйна, он будет заполнен нулями.

**Comment by avasyukov** [comment]
Справедливо. Здесь уже я не обратил внимания, что массив объявлен как global. Да, тогда он у вас исходно заполнен нулями. Решение работать будет.

Но будьте морально готовы, что раз вы на это закладываете принципиальную работоспособность программы, то на сдаче я спрошу, всегда ли это так, и когда может случиться, что там окажутся не нули.

**Comment by Avalanche736** [comment]
У меня все же не получилось отладить программу на этой идее, вечно для
исправления косяков приходилось добавлять ещё и ещё счетчики, что их стало
слишком много. Пришлось в корне пересмотреть идею.

31 окт. 2017 г. 17:42 пользователь "Alexey Vasyukov" <
notifications@github.com> написал:

Справедливо. Здесь уже я не обратил внимания, что массив объявлен как
global. Да, тогда он у вас исходно заполнен нулями. Решение работать будет.

Но будьте морально готовы, что раз вы на это закладываете принципиальную
работоспособность программы, то на сдаче я спрошу, всегда ли это так, и
когда может случиться, что там окажутся не нули.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Avalanche736/1-zadanie/issues/1#issuecomment-340783858>,
or mute the thread
